import React from 'react';
import { X, CheckCircle, XCircle, HelpCircle, BarChart2 } from 'lucide-react';

const TEST_DETAILS_DICTIONARY = {
  "Frequency (Monobit)": {
    purpose: "Tests the proportion of zeros and ones in the sequence. Determines whether the number of ones and zeros are approximately equal.",
    formula: "S_obs = |Sum(X_i)| / sqrt(n),  P-value = erfc(S_obs / sqrt(2))",
    interpretation: "Passing means the bit stream has equal proportions of 0s and 1s. Failing indicates extreme bias towards 0s or 1s."
  },
  "Block Frequency": {
    purpose: "Tests the proportion of ones within fixed M-bit blocks across the sequence.",
    formula: "Chi^2 = 4 * M * Sum((pi_i - 0.5)^2),  P-value = igamc(N/2, Chi^2/2)",
    interpretation: "Passing means bit proportions remain locally balanced in each M-bit block without regional clustering."
  },
  "Cumulative Sums (Forward)": {
    purpose: "Tests the maximal excursion of the random walk created by cumulative sums of sequence bits.",
    formula: "Z = max|S_k|, calculates excursion probability under Wiener process bounds.",
    interpretation: "Passing means the cumulative sum random walk stays within expected standard deviation bounds."
  },
  "Cumulative Sums (Reverse)": {
    purpose: "Tests maximal random walk excursion starting from the end of the bit sequence.",
    formula: "Z = max|S_k_rev|, evaluates random walk symmetry from right to left.",
    interpretation: "Passing indicates reverse random walk stability without directional drift."
  },
  "Runs": {
    purpose: "Tests the total number of runs (uninterrupted sequences of identical bits).",
    formula: "V_obs = 1 + Sum(X_i != X_{i+1}), evaluates oscillation rate between 0 and 1.",
    interpretation: "Passing means transitions between 0s and 1s occur at an expected random rate (neither too fast nor too slow)."
  },
  "Longest Run of Ones": {
    purpose: "Evaluates the longest run of ones in M-bit blocks compared to expected theoretical length.",
    formula: "Chi^2 goodness-of-fit against theoretical block run length distributions.",
    interpretation: "Passing indicates that maximum streak lengths of consecutive 1s conform to random expectations."
  },
  "Binary Matrix Rank": {
    purpose: "Tests linear dependence among fixed-length substrings using rank calculations of 32x32 binary matrices over GF(2).",
    formula: "Matrix rank via Gaussian elimination over GF(2), compared against Chi^2 distribution.",
    interpretation: "Passing means sub-blocks are linearly independent. Failing indicates linear dependencies or periodic repetitions."
  },
  "Discrete Fourier Transform (FFT)": {
    purpose: "Detects periodic features or repetitive spectral peaks in the bit stream via Fast Fourier Transform.",
    formula: "Peak count threshold d = (N1 - N0) / sqrt(n * 0.95 * 0.05 / 4).",
    interpretation: "Passing means the frequency spectrum is flat (white noise behavior). Failing reveals hidden periodicities or signals."
  },
  "Approximate Entropy": {
    purpose: "Compares the frequency of overlapping block patterns of length m and m+1 across the entire sequence.",
    formula: "ApEn = Phi(m) - Phi(m+1), Chi^2 = 2 * n * (ln(2) - ApEn).",
    interpretation: "Passing means pattern complexity matches expected random sequence entropy."
  },
  "Serial (Test 1)": {
    purpose: "Determines whether the frequency of all 2^m m-bit overlapping patterns is uniform.",
    formula: "Psi^2 statistics over m-bit overlapping pattern counts.",
    interpretation: "Passing indicates that all possible m-bit sub-words occur with equal uniform frequency."
  },
  "Serial (Test 2)": {
    purpose: "Secondary non-overlapping sub-pattern uniformity test.",
    formula: "Delta^2 Psi^2 pattern variance test.",
    interpretation: "Passing confirms higher-order sub-pattern independence."
  },
  "Linear Complexity": {
    purpose: "Evaluates sequence complexity using the Berlekamp-Massey algorithm for Linear Feedback Shift Registers (LFSR).",
    formula: "Berlekamp-Massey shortest LFSR length evaluation over M-bit blocks.",
    interpretation: "Passing means the sequence cannot be generated by a short linear feedback shift register."
  }
};

export default function TestResultModal({ test, onClose }) {
  if (!test) return null;

  const details = TEST_DETAILS_DICTIONARY[test.name] || {
    purpose: "Evaluates statistical randomness properties under NIST SP 800-22 specifications.",
    formula: "Standard NIST SP 800-22 P-value calculation formula.",
    interpretation: "P-value >= α (0.01) indicates sequence properties adhere to random expectations."
  };

  const isPass = test.status === 'PASS';

  return (
    <div style={{
      position: 'fixed',
      inset: 0,
      background: 'rgba(5, 8, 15, 0.85)',
      backdropFilter: 'blur(10px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 100,
      padding: '20px'
    }}>
      <div className="glass-panel" style={{
        maxWidth: '650px',
        width: '100%',
        padding: '28px',
        position: 'relative',
        border: isPass ? '1px solid rgba(16, 185, 129, 0.4)' : '1px solid rgba(239, 68, 68, 0.4)',
        boxShadow: isPass ? '0 0 40px rgba(16, 185, 129, 0.15)' : '0 0 40px rgba(239, 68, 68, 0.15)'
      }}>
        {/* Close Button */}
        <button
          onClick={onClose}
          style={{
            position: 'absolute',
            top: '18px',
            right: '18px',
            background: 'transparent',
            border: 'none',
            color: '#94a3b8',
            cursor: 'pointer'
          }}
        >
          <X size={22} />
        </button>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '20px' }}>
          {isPass ? <CheckCircle size={36} color="#34d399" /> : <XCircle size={36} color="#f87171" />}
          <div>
            <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: '#f8fafc' }}>
              {test.name}
            </h2>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginTop: '4px' }}>
              <span className={isPass ? 'badge-pass' : 'badge-fail'}>
                {test.status}
              </span>
              <span style={{ fontSize: '0.8rem', color: '#94a3b8' }}>
                Significance Level: <strong>α = 0.01</strong>
              </span>
            </div>
          </div>
        </div>

        {/* Metrics Grid */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '12px',
          background: 'rgba(13, 19, 34, 0.8)',
          padding: '16px',
          borderRadius: '10px',
          marginBottom: '20px',
          border: '1px solid rgba(255, 255, 255, 0.05)'
        }}>
          <div>
            <div style={{ fontSize: '0.75rem', color: '#94a3b8', textTransform: 'uppercase' }}>P-Value</div>
            <div style={{ fontSize: '1.25rem', fontWeight: 700, color: isPass ? '#34d399' : '#f87171', fontFamily: 'Fira Code' }}>
              {typeof test.p_value === 'number' ? test.p_value.toFixed(6) : test.p_value}
            </div>
          </div>

          <div>
            <div style={{ fontSize: '0.75rem', color: '#94a3b8', textTransform: 'uppercase' }}>Uniformity (p_T)</div>
            <div style={{ fontSize: '1.25rem', fontWeight: 700, color: '#38bdf8', fontFamily: 'Fira Code' }}>
              {typeof test.p_uniformity === 'number' ? test.p_uniformity.toFixed(4) : (test.p_uniformity || 'N/A')}
            </div>
          </div>

          <div>
            <div style={{ fontSize: '0.75rem', color: '#94a3b8', textTransform: 'uppercase' }}>Pass Ratio</div>
            <div style={{ fontSize: '1.25rem', fontWeight: 700, color: '#a78bfa', fontFamily: 'Fira Code' }}>
              {typeof test.pass_ratio === 'number' ? `${(test.pass_ratio * 100).toFixed(1)}%` : '100%'}
            </div>
          </div>
        </div>

        {/* Explanation Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', fontSize: '0.85rem', color: '#cbd5e1' }}>
          <div>
            <strong style={{ color: '#38bdf8' }}>Mathematical Purpose:</strong>
            <p style={{ marginTop: '4px', lineHeight: '1.5' }}>{details.purpose}</p>
          </div>

          <div>
            <strong style={{ color: '#818cf8' }}>Formula / Metric:</strong>
            <div style={{
              background: '#090d16',
              padding: '8px 12px',
              borderRadius: '6px',
              marginTop: '4px',
              fontFamily: 'Fira Code',
              color: '#34d399',
              fontSize: '0.8rem'
            }}>
              {details.formula}
            </div>
          </div>

          <div>
            <strong style={{ color: isPass ? '#34d399' : '#f87171' }}>Statistical Interpretation:</strong>
            <p style={{ marginTop: '4px', lineHeight: '1.5' }}>{details.interpretation}</p>
          </div>
        </div>

        {/* Action button */}
        <div style={{ marginTop: '24px', textAlign: 'right' }}>
          <button onClick={onClose} className="custom-button">
            Close Analysis
          </button>
        </div>
      </div>
    </div>
  );
}
