import os
import secrets
import math
import time

def calculate_shannon_entropy(bit_string: str) -> float:
    if not bit_string:
        return 0.0
    n = len(bit_string)
    ones = bit_string.count('1')
    zeros = n - ones
    
    p0 = zeros / n
    p1 = ones / n
    
    entropy = 0.0
    if p0 > 0:
        entropy -= p0 * math.log2(p0)
    if p1 > 0:
        entropy -= p1 * math.log2(p1)
        
    return round(entropy, 6)

def generate_trng_bits(source_type: str, num_bits: int) -> dict:
    needed_bytes = (num_bits + 7) // 8
    
    src_lower = source_type.lower()
    
    if "jitter" in src_lower:
        # Software microsecond execution jitter entropy harvester
        collected_bytes = bytearray()
        for _ in range(needed_bytes):
            acc = 0
            for b in range(8):
                t1 = time.perf_counter_ns()
                # Dummy CPU loop to measure microscopic scheduler jitter
                s = 0
                for i in range(50):
                    s += i
                t2 = time.perf_counter_ns()
                bit = (t2 - t1) & 1
                acc = (acc << 1) | bit
            collected_bytes.append(acc)
        bit_string = "".join(f"{b:08b}" for b in collected_bytes)[:num_bits]
        source_name = "CPU Hardware Timing Jitter Simulation"
    else:
        # OS System Entropy Pool (CryptGenRandom / /dev/urandom)
        raw_bytes = secrets.token_bytes(needed_bytes)
        bit_string = "".join(f"{b:08b}" for b in raw_bytes)[:num_bits]
        source_name = "OS System Entropy Pool (urandom/CryptGenRandom)"

    entropy_val = calculate_shannon_entropy(bit_string)

    return {
        "bits": bit_string,
        "source": source_name,
        "num_bits": len(bit_string),
        "entropy": entropy_val,
        "max_entropy": 1.0,
        "is_physical_hardware": False,
        "category": "TRNG Simulation / OS Entropy",
        "disclaimer": "CRITICAL NOTICE: This is an OS entropy / CPU jitter software harvester simulation. It is NOT generated by a dedicated physical hardware TRNG diode or physical particle sensor.",
        "security_note": "OS entropy pools combine system interrupts and hardware events. While cryptographically suitable for key generation on modern OS, statistical testing evaluates output bits, not physical device mechanics."
    }
